# Generated by Django 3.2.6 on 2022-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='about',
            new_name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='disease',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
