# Generated by Django 3.2.6 on 2022-03-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220312_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('symptom', models.CharField(max_length=250)),
                ('precautions', models.CharField(max_length=250)),
                ('cures', models.CharField(max_length=250)),
            ],
        ),
    ]
